### ISSUE TITLE
new navbar

### ISSUE THREAD

**Issue by zacdavidm** [TheAndroidMaster/TheAndroidMaster.github.io#1]
<nav class="navbar navbar-default">
  <div class="container-fluid">
    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><button id="index" type="button" class="btn btn-primary" href="theandroidmaster.github.io/index.html">Index</button></li>
        <li><div class="btn-group" role="group" aria-label="...">
    
    <button id="action" type="button" class="btn btn-default">Action</button>
    <button id="adventure" type="button" class="btn btn-default">Adventure</button>
    <button id="arcade" type="button" class="btn btn-default">Arcade</button>
    <button id="puzzle" type="button" class="btn btn-default">Puzzle</button>
    <button id="strategy" type="button" class="btn btn-default">Strategy</button>
    <button id="sports" type="button" class="btn btn-default">Sports</button>
    <button id="other" type="button" class="btn btn-default">Other</button>
  </div></li>
  <li><button id="chat" type="button" class="btn btn-default">Chatroom</button></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
    </div>
  </div>
</nav>

**Comment by TheAndroidMaster** [comment]
I has made it done.
