### ISSUE TITLE
Chat service bugs

### ISSUE THREAD

**Issue by crutchcorn** [TheAndroidMaster/TheAndroidMaster.github.io#2]
- [x] Can run HTML/JS (using onclick and similar) [We should move to markdown]
- [ ] Some characters (like +) don't show up at all
- [ ] Putting  # in a comment changes the user's color to red
- [x] Any text after a colon gets cut off from the rest of the comment
- [x] Chat clears every so often without explaination (THIS ANGERS ME GREATLY)
- [x] Doesn't always show when user has left

**Comment by TheAndroidMaster** [comment]
The chat-clear bug has finally been fixed! The chatroom now relies on the browser to keep a record of the chat, meaning that it clears if you reload. This makes it a lot more efficient in sending and receiving messages, but has created a few small bugs which should be pretty easy to fix.

**Comment by TheAndroidMaster** [comment]
Chatroom doesn't exist anymore. Closing issue :P
