### ISSUE TITLE
Inconsistent highlighting

### ISSUE THREAD

**Issue by chinmaykunkikar** [TheAndroidMaster/TheAndroidMaster.github.io#24]
1. Project pages that include **License** ([example](https://jfenn.me/projects/asteroid/)) are highlighted as **SQL**.

2. There is inconsistent highlighting in code boxes in [some projects](https://jfenn.me/projects/aah/).

3. [This](https://github.com/TheAndroidMaster/TheAndroidMaster.github.io/blob/master/_includes/head-highlightjs.html#L5) adds script to the html even if the `*.min.js` is not being used anywhere in the file.These are the source languages, that are mentioned in the markdowns of projects.

**Comment by chinmaykunkikar** [comment]
[Not Issue] Can you show a proper way to run this site locally? I tried running `jekyll serve` after cloning but it doesn't have any styles. I cannot run `bundle exec jekyll s` because I don't see a Gemfile here.

**Comment by TheAndroidMaster** [comment]
This is a side effect of the markdown parser that I'm not sure how to deal with - it doesn't do anything with the specified language in the output HTML, so there isn't really any way I can tell highlightjs which specific block styles apply to.

As for building the project, you should have a folder titled "css" that pulls from [TheAndroidMaster/styles](https://github.com/TheAndroidMaster/styles). If you're using a non-standard gît client that doesn't support submodules, you may have to just find the commit it references (err, click on the css folder in GitHub and it'll go to it) and download its contents into the folder manually.

Another possibility is that it's ignoring the current commit and pulling the latest version of the repo, which doesn't actually contain any css (as detailed in the README, it is in a different branch). The `bem-css` branch of this repository is using the latest version (and should be merged into master soon anyway - I'm nearly done with it).

Yet another possibility is that you're already on the the `bem-css` branch, the SCSS from the styles repo is there, but Jekyll build is ignoring it for whatever reason and no CSS is being output. In that case, you can grab a generated version of the new css from [jfenn.me/photos/css/styles.css](https://jfenn.me/photos/css/styles.css), which uses it already, and just shove it in the CSS folder.

**Comment by TheAndroidMaster** [comment]
Correction: the language specified does affect the generated html, I just wasn't sure how it affected the behavior of highlightjs. I haven't had my daily caffeine yet. Apparently highlightjs will try to "guess" the language of a block if none is specified (causing the rogue SQL licenses), but this can be disabled for individual blocks by specifying the language as `nohighlight`.

**Comment by chinmaykunkikar** [comment]
> As for building the project, you should have a folder titled "css" that pulls from [TheAndroidMaster/styles](https://github.com/TheAndroidMaster/styles). If you're using a non-standard gît client that doesn't support submodules, you may have to just find the commit it references (err, click on the css folder in GitHub and it'll go to it) and download its contents into the folder manually.
> 

Ah thanks! I thought of that too but there was already as `css` subdirectory. Never saw that it was empty. I did a quick `submodule update` and it's working all fine.

> Correction: the language specified does affect the generated html, I just wasn't sure how it affected the behavior of highlightjs. I haven't had my daily caffeine yet. Apparently highlightjs will try to "guess" the language of a block if none is specified (causing the rogue SQL licenses), but this can be disabled for individual blocks by specifying the language as `nohighlight`.
> 

Yes I looked it up too. It will be a tiring process.
What can be done is that the license blocks can have their own classes that use the `nohighight` property. Perhaps a function can be written or so to identify `## License` from markdowns or something along those lines (pardon me, I'm just getting started in web development).


This site is a great work though. I am working on my own site and this site has given me a great deal of ideas. The way you have managed to keep it minimal, modern and less stressful to browser is worth appreciating. Thanks.

**Comment by TheAndroidMaster** [comment]
> Perhaps a function can be written or so to identify ## License from markdowns

The project pages are all actually generated by [this undocumented NodeJS script](https://github.com/TheAndroidMaster/TheAndroidMaster.github.io/blob/master/.scripts/update.js), so it would actually be quite easy to just add "nohighlight" to every code block that doesn't specify a language.
